# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1yeKDMCceHY6JfcRspW0dBAc01MPB4e

swiggy/zomato food delivery analysis

*   company wants to imporve delivery performance and satosfaction
*   practical tasks
1.analyze delivery data



> Add blockquote
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.DataFrame({'ordertime':[2,3,4,4,6],#in clock time
'deliverytime':[2.20,3.30,4.40,4.45,6.35],
'deliverypartner':["swiggy","zomato","blinkit","swiggy","zomato"],
'area':['a','b','c','d','e'],
'ratings':[3,4,5,2,4]
})
for i in range(len(df['ordertime'])):
  print(df['ordertime'][i],df['deliverytime'][i],df['deliverypartner'][i],df['area'][i],df['ratings'][i])
  df

avg_deliverytime=np.mean(deliverytime)
print(avg_deliverytime)

peak_order_hours=df['ordertime'].mode()[0]
print("this is the peak ordering time:",peak_order_hours)

delay_time=df['deliverytime']-df['ordertime']
print(delay_time)

most_delayed_time=delay_time.max()
print("this is the most delayed time:",most_delayed_time)

index = delay_time.idxmax()

print("Maximum delay:", delay_time[index])
print("delayed delivery area:", df['area'][index])

index1=df['ratings'].idxmax()
print("top rating partner:",df['deliverypartner'][index1])

plt.bar(df['area'],delay_time)
plt.show()

df1=df.groupby('deliverypartner')['ratings'].mean()
print(df1)

plt.pie(df1,labels=df1.index,autopct='%1.1f%%')
plt.show()

"""ekart analysis
tasks=most sold product,high revenue customers,most used payment methods,products with poor ratings
"""

customer_name=['nanda','luca','vicky','don','rithu']
product_purchases=['shoe','shirt','pant','sunscreen','mobile']
cart_abandment=[1,1,0,1,2]
product_buy=[1,2,1,3,0]
customer_ratings=[4,5,2,5,1]
payment_methods=['a','a','b','a','b']
sales=[100,200,150,300,250]
df=pd.DataFrame({'product_purchases':product_purchases,'cart_abandment':cart_abandment,'customer_ratings':customer_ratings,'payment_methods':payment_methods,'product_buy':product_buy,'sales':sales,'customer_name':customer_name})
df

d=df.groupby('product_buy')['product_purchases'].count()
print(d)

plt.bar(df['product_purchases'],df['product_buy'])
plt.title("quantity of products purchased")
plt.show()

plt.pie(df['sales'],labels=df['customer_name'],autopct='%1.1f%%')
plt.title("revenue generated from customer")
plt.show()

most_used_payment_method=df['payment_methods'].mode()[0]
print("this is the most used payment method:",most_used_payment_method)

plt.plot(df['product_purchases'],df['customer_ratings'])
plt.title("ratings of products")
plt.show()

transaction_amount=[20001,20010,21,102000,58]
loc=['mpl','atp','bnglr','hyd','munnar']
country=['ind','ind','ind','pak','bang']
account_activity=['savings','current','savings','current','savings']
df=pd.DataFrame({'transaction_amount':transaction_amount,'loc':loc,'account_activity':account_activity,'country':country})
df

fraud=df[df['transaction_amount']>100000]
fraud

df1=df[(df['transaction_amount']>20000) & (df['account_activity']=='savings')]
print("these are high risk accounts\n")
df1

df2=df[(df['transaction_amount']>20000)|(df['country']!='ind')]
df2

plt.bar(df['country'],df['transaction_amount'])
plt.show()

day=[1,2,3,4,5,6,7]
productnames=['paracetmol','zintac','citrizin','amrodil','painkiller','move','saridon']
daliy_sales=[230,240,221,231,311,237,119]

product_stock=[210,130,242,341,328,143,189]
epiry_dates=[4,6,12,3,4,2,6]
seasonal_demand=['sum','win','win','win','sum','win','sum']
df=pd.DataFrame({'day':day,'productnames':productnames,'daliy_sales':daliy_sales,'product_stock':product_stock,'epiry_dates':epiry_dates,'seasonal_demand':seasonal_demand})
df

index=df['daliy_sales'].idxmax()
print("daily maxi sales",df['daliy_sales'].max(),"fast moving productname:",df['productnames'][index])
index=df['daliy_sales'].idxmin()

print("daily min sales",df['daliy_sales'].min(),"slow moving productname:",df['productnames'][index])

plt.bar(df['productnames'],df['daliy_sales'])
plt.show()

