# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgdIwHWaGck93t2qvY9BuHNAtYn4Iqdv
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

marks=[78,98,67,90,67]
hrs=[2,3,1,3,1]
print("median",np.median(marks))
print("mean",np.mean(marks))
print("variance",np.var(marks))
print("std deviation",np.std(marks))
print("corelation",np.corrcoef(marks))
plt.plot(marks,hrs)
plt.show()

